### ISSUE TITLE
Logo for book

### ISSUE THREAD

**Issue by TomasBeuzen** [UBC-MDS/py-pkgs#10]
@ttimbers - I thought it would be cool to make a little logo we could pin to the book. I was messing around this morning and came up with these two options. Let me know what you think. This is a low priority task - no rush.

![py-pkg-logos](https://user-images.githubusercontent.com/40379073/74610124-1c216d00-50a5-11ea-829a-fd339c2fe91f.png)

**Comment by ttimbers** [comment]
I LOVE your enthusiasm, and think this is a great idea! I really like the second one! Can we make a hex sticker with it next?

**Comment by TomasBeuzen** [comment]
Here's an example of a hex sticker (using same colour scheme as `reticulate`'s sticker (which seemed appropriate). I've uploaded the .png's/.svg's [here](https://github.com/UBC-MDS/py-pkgs/tree/master/docs/logo) so we can revisit them and modify later.

![py-pkgs-hex](https://user-images.githubusercontent.com/40379073/74610883-f9df1d80-50ab-11ea-9e80-1426d37763f5.png)

**Comment by ttimbers** [comment]
LOVE ❤️
