### ISSUE TITLE
Creating an actual "py-pkgs" package on PyPI

### ISSUE THREAD

**Issue by TomasBeuzen** [UBC-MDS/py-pkgs#16]
We use the hypothetical `foocat` package throughout the book at the moment. But in all chapters after "The Whole Game" it would be great to have this package available on pypi so that readers can actually pip install it and run through the code. Even better, we could pip install it so that later chapters can actually execute the code they are showing, rather than having it embedded in markdown.

**Comment by ttimbers** [comment]
LOVE this idea! I will add you to repo `foocat` repo as a collaborator so you can work on this.

**Comment by ttimbers** [comment]
Turns out I did this (see: https://pypi.org/project/foocat/) - but the package there is WAY behind what I have on test PyPI... (see: https://test.pypi.org/project/foocat/)

I think I need we need to setup the CD GitHub actions workflows to send to both package indices...

**Comment by TomasBeuzen** [comment]
Perfect! (and honestly I'm surprised that the name foocat was available)

I'd like to have a go at fixing this all up if you don't mind. It would be useful for me to go through it all before starting to right the CI chapter.

**Comment by ttimbers** [comment]
For sure!

**Comment by TomasBeuzen** [comment]
Exists here now: https://pypi.org/project/pypkgs/
