### ISSUE TITLE
All proposed chapters drafted

### ISSUE THREAD

**Issue by TomasBeuzen** [UBC-MDS/py-pkgs#19]
All proposed chapters have been drafted and published [here](https://ubc-mds.github.io/py-pkgs/content/00-preface.html). Each chapter needs a proof read(s). I'm creating this issue to document the proofing stage:

- [ ] System setup
- [ ] The Whole Game
- [ ] Package Structure & State
- [ ] Testing
- [ ] Documentation
- [ ] Releasing & versioning
- [ ] Continuous Integration & Deployment
- [ ] Packages with Command Line Interfaces
- [ ] The Py-Pkgs Cheat Sheet

Once a chapter has been proofed, we can close the associated issue.

**Comment by ttimbers** [comment]
This is amazing! You're an absolute machine! I will start reviewing these this week. I guess I could estimate one chapter per work, given my other work?

Also, we should start to think about a book proposal. What do you think about pitching to O'Reilly first?

**Comment by TomasBeuzen** [comment]
Sure thing - no pressure! I'm going to read it front-to-back too.

As discussed on Slack - we will start looking into the proposal process with O'Reilly to get the ball rolling.

**Comment by TomasBeuzen** [comment]
This is now tracked in the ["Chapter Review" project board](https://github.com/UBC-MDS/py-pkgs/projects/4)
