### ISSUE TITLE
Issue on page /chapters/07-ci-cd.html - copy code feature

### ISSUE THREAD

**Issue by SamEdwardes** [UBC-MDS/py-pkgs#23]
The feature to copy example code is really nice. Right now when I copy the code it includes extra characters at the start that interfere with copy and pasting into the command line. 

For example, when I click here: 

![image](https://user-images.githubusercontent.com/18248949/91682731-5913f500-eb07-11ea-922d-c6e5bad80a2d.png)

This is what is copied to my clipboard:

```
$ poetry add --dev python-semantic-release
```

Ideally it would just copy this:

```
poetry add --dev python-semantic-release
```

I noticed a few others spots as well throughout the book where this is the case.

Thank you again for creating this great resource!

**Comment by TomasBeuzen** [comment]
Thanks @SamEdwardes - just fixed this, hopefully I caught them all!
