### ISSUE TITLE
Issue on page /03-how-to-package-a-python.html -- No module named 'autoapi'

### ISSUE THREAD

**Issue by fegue** [UBC-MDS/py-pkgs#58]
When trying to render the documentation, I encountered the following error:
```python
cd docs
poetry run make html

```
```console
Running Sphinx v3.5.4
Extension error:
Could not import extension autoapi.extension (exception: No module named 'autoapi')
make: *** [Makefile:19: html] Error 2
```

I solved the issue by adding `sphinx-autoapi` to the pyproject.toml file.
```python
poetry add --dev sphinx nbsphinx ipykernel sphinx-autoapi
```

**Comment by TomasBeuzen** [comment]
Thank you very much for raising this @fegue! We've just recently made several changes to the Cookiecutter and the "How to package a Python" chapter (currently on the redevelopment branch) which we hope to merge soon, but in the meantime there may be a few inconsistencies like this so please do reach out - much appreciated!
